<?php

return [
    'table_headers' => [
        'Action',
        'Nomor',
        'Nama Customer',
        'Vendor Pelayaran Forwarding',
        'POL',
        'POD',
        'UK CONTAINER',
        'Jenis Container',
        'Jenis Order',
        'Commodity',
        'Service',
        'THC POL Incl',
        'THC POL',
        'LOLO POL Dalam Luar',
        'LOLO POL Incl',
        'THC POD Incl',
        'THC POD',
        'LOLO POD Dalam Luar',
        'LOLO POD Incl',
        'Status',
        'Rework Incl',
        'Nominal Rework',
        'Keterangan Rework',
        'Buruh Muat Incl',
        'HPP Biaya Buruh Muat',
        'Alat Berat POL Incl',
        'Nominal Alat Berat POL',
        'Keterangan Alat Berat POL',
        'Buruh Stripping Incl',
        'HPP Biaya Buruh Stripping',
        'Buruh Bongkar Incl',
        'HPP Biaya Buruh Bongkar',
        'Alat Berat POD Stripping Incl',
        'Nominal Alat Berat POD Stripping',
        'Keterangan Alat Berat POD Stripping',
        'Alat Berat POD Bongkar Incl',
        'Nominal Alat Berat POD Bongkar',
        'Keterangan Alat Berat POD Bongkar',
        'Asuransi Incl',
        'Nominal TSI',
        'Persen Asuransi',
        'Truck POL Incl',
        'Rute Truck POL',
        'Truck POD Incl',
        'Rute Truck POD',
        'Fee Agent POL Incl',
        'Nominal Fee Agent POL',
        'Keterangan Fee Agent POL',
        'Fee Agent POD Incl',
        'Nominal Fee Agent POD',
        'Keterangan Fee Agent POD',
        'Toeslag Incl',
        'Nominal Toeslag',
        'Keterangan Toeslag',
        'Seal Incl',
        'HPP Biaya Seal',
        'Ops Incl',
        'Kode HPP Biaya Ops',
        'Karantina Incl',
        'Nominal Karantina',
        'Keterangan Karantina',
        'Cashback Incl',
        'Nominal Cashback',
        'Keterangan Cashback',
        'Claim Incl',
        'Nominal Claim',
        'Keterangan Claim',
        'Biaya Lain Incl',
        'BL Incl',
        'Nominal BL',
        'Keterangan BL',
        'DO Incl',
        'Nominal DO',
        'Keterangan DO',
        'APBS Incl',
        'Nominal APBS',
        'Keterangan APBS',
        'Cleaning Incl',
        'Nominal Cleaning',
        'Keterangan Cleaning',
        'Doc Incl',
        'Nominal Doc',
        'Keterangan Doc',
        'Sudah Diapprove',
        'Sudah Jadi JOA'
    ],
    'columns_shown' => [
        'NOMOR',
        'NAMA_CUSTOMER',
        'VENDOR_PELAYARAN_FORWARDING',
        'POL',
        'POD',
        'UK_CONTAINER',
        'JENIS_CONTAINER',
        'JENIS_ORDER',
        'COMMODITY',
        'SERVICE',
        'THC_POL_INCL',
        'THC_POL',
        'LOLO_POL_DALAM_LUAR',
        'LOLO_POL_INCL',
        'THC_POD_INCL',
        'THC_POD',
        'LOLO_POD_DALAM_LUAR',
        'LOLO_POD_INCL',
        'STATUS',
        'REWORK_INCL',
        'NOMINAL_REWORK',
        'KETERANGAN_REWORK',
        'BURUH_MUAT_INCL',
        'HPP_BIAYA_BURUH_MUAT',
        'ALAT_BERAT_POL_INCL',
        'NOMINAL_ALAT_BERAT_POL',
        'KETERANGAN_ALAT_BERAT_POL',
        'BURUH_STRIPPING_INCL',
        'HPP_BIAYA_BURUH_STRIPPING',
        'BURUH_BONGKAR_INCL',
        'HPP_BIAYA_BURUH_BONGKAR',
        'ALAT_BERAT_POD_STRIPPING_INCL',
        'NOMINAL_ALAT_BERAT_POD_STRIPPING',
        'KETERANGAN_ALAT_BERAT_POD_STRIPPING',
        'ALAT_BERAT_POD_BONGKAR_INCL',
        'NOMINAL_ALAT_BERAT_POD_BONGKAR',
        'KETERANGAN_ALAT_BERAT_POD_BONGKAR',
        'ASURANSI_INCL',
        'NOMINAL_TSI',
        'PERSEN_ASURANSI',
        'TRUCK_POL_INCL',
        'RUTE_TRUCK_POL',
        'TRUCK_POD_INCL',
        'RUTE_TRUCK_POD',
        'FEE_AGENT_POL_INCL',
        'NOMINAL_FEE_AGENT_POL',
        'KETERANGAN_FEE_AGENT_POL',
        'FEE_AGENT_POD_INCL',
        'NOMINAL_FEE_AGENT_POD',
        'KETERANGAN_FEE_AGENT_POD',
        'TOESLAG_INCL',
        'NOMINAL_TOESLAG',
        'KETERANGAN_TOESLAG',
        'SEAL_INCL',
        'HPP_BIAYA_SEAL',
        'OPS_INCL',
        'HPP_BIAYA_OPS',
        'KARANTINA_INCL',
        'NOMINAL_KARANTINA',
        'KETERANGAN_KARANTINA',
        'CASHBACK_INCL',
        'NOMINAL_CASHBACK',
        'KETERANGAN_CASHBACK',
        'CLAIM_INCL',
        'NOMINAL_CLAIM',
        'KETERANGAN_CLAIM',
        'BIAYA_LAIN_INCL',
        'BL_INCL',
        'NOMINAL_BL',
        'KETERANGAN_BL',
        'DO_INCL',
        'NOMINAL_DO',
        'KETERANGAN_DO',
        'APBS_INCL',
        'NOMINAL_APBS',
        'KETERANGAN_APBS',
        'CLEANING_INCL',
        'NOMINAL_CLEANING',
        'KETERANGAN_CLEANING',
        'DOC_INCL',
        'NOMINAL_DOC',
        'KETERANGAN_DOC',
        'SUDAH_DIAPPROVE',
        'SUDAH_JADI_JOA'
    ],
    'table_headers_truck_price' =>
    ['Action', 'Kode', 'Rute Truck', 'Customer', 'Nama Commodity', 'Nama Truck', 'Berlaku', 'Harga Jual', 'Keterangan'],
    'columns_shown_truck_price' => ['KODE', 'NAMA_RUTE_TRUCK', 'NAMA_CUSTOMER', 'NAMA_COMMODITY', 'NAMA_TRUCK', 'BERLAKU', 'HARGA_JUAL', 'KETERANGAN'],
    'table_headers_harga_lcl' => ['Action', 'Kode', 'Produk', 'POL', 'POD', 'Rumus', 'Kategori', 'Harga Jual', 'Berlaku', 'Customer'],
    'columns_shown_harga_lcl' => ['KODE',  'NAMA_PRODUK', 'NAMA_POL', 'NAMA_POD', 'NAMA_RUMUS', 'NAMA_KATEGORI', 'HARGA_JUAL', 'BERLAKU', 'NAMA_CUSTOMER'],

    'table_headers_penawaran' => ['Action', 'Kode', 'Jenis Order', 'Tanggal', 'Rate Status', 'Customer', 'Status', 'PPN', 'PPH', 'Payment', 'TOP', 'Keterangan TOP', 'Keterangan Tambahan', 'Sales'],
    'columns_shown_penawaran' => ['KODE',  'KODE_JENIS_ORDER', 'TANGGAL', 'RATE_STATUS', 'KODE_CUSTOMER', 'STATUS', 'PPN', 'PPH', 'PAYMENT', 'TOP', 'KETERANGAN_TOP', 'KETERANGAN_TAMBAHAN', 'SALES'],


];
